# Generated by Django 3.2 on 2023-03-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='managementIdpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.CharField(default='', max_length=30, verbose_name='管理端用户账号')),
                ('password', models.CharField(default='', max_length=30, verbose_name='管理端密码')),
            ],
            options={
                'verbose_name': '管理端账号和密码',
                'verbose_name_plural': '管理端账号和密码',
                'db_table': 'manager_data',
            },
        ),
    ]
