# Generated by Django 3.2 on 2023-03-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_all_function', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_base_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=30, verbose_name='用户账号')),
                ('name', models.CharField(default='', max_length=11, verbose_name='名字')),
                ('date', models.CharField(default='', max_length=20, verbose_name='日期')),
                ('time', models.IntegerField(default='', verbose_name='时间')),
                ('term', models.IntegerField(default='', verbose_name='期数')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '基础信息',
                'verbose_name_plural': '基础信息',
                'db_table': 'base_data',
            },
        ),
        migrations.CreateModel(
            name='change_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=30, verbose_name='用户账号')),
                ('name', models.CharField(default='', max_length=11, verbose_name='名字')),
                ('old_date', models.CharField(default='', max_length=20, verbose_name='原研学日期')),
                ('old_time', models.IntegerField(default='', verbose_name='原研学时间')),
                ('new_date', models.CharField(default='', max_length=20, verbose_name='新研学日期')),
                ('new_time', models.IntegerField(default='', verbose_name='新研学时间')),
                ('reason', models.CharField(default='', max_length=50, verbose_name='原因')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '调换信息',
                'verbose_name_plural': '调换信息',
                'db_table': 'change_data',
            },
        ),
        migrations.CreateModel(
            name='leave_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=30, verbose_name='用户账号')),
                ('name', models.CharField(default='', max_length=11, verbose_name='名字')),
                ('old_date', models.CharField(default='', max_length=20, verbose_name='原研学日期')),
                ('old_time', models.IntegerField(default='', verbose_name='原研学时间')),
                ('reason', models.CharField(default='', max_length=50, verbose_name='原因')),
                ('is_delete', models.BooleanField(default=True, verbose_name='是否已删除')),
            ],
            options={
                'verbose_name': '请假信息',
                'verbose_name_plural': '请假信息',
                'db_table': 'leave_data',
            },
        ),
    ]
