# Generated by Django 3.2 on 2023-03-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invitationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.CharField(default='', max_length=20, verbose_name='邀请码')),
            ],
            options={
                'verbose_name': '邀请码列表',
                'verbose_name_plural': '邀请码列表',
                'db_table': 'invitation_codes',
            },
        ),
        migrations.CreateModel(
            name='logAndsign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=30, verbose_name='用户账号')),
                ('password', models.CharField(default='', max_length=30, verbose_name='用户密码')),
            ],
            options={
                'verbose_name': '用户账号和密码',
                'verbose_name_plural': '用户账号和密码',
                'db_table': 'user_data',
            },
        ),
    ]
