# Generated by Django 3.2 on 2023-03-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_log', '0004_auto_20230313_0618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logandsign',
            options={'ordering': ['number_of_session'], 'verbose_name': '用户账号和密码', 'verbose_name_plural': '用户账号和密码'},
        ),
    ]
