# Generated by Django 3.2 on 2023-03-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='managerIdPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_id', models.CharField(default='', max_length=20, verbose_name='管理员账号')),
                ('manager_pass', models.CharField(default='', max_length=100, verbose_name='管理员密码')),
            ],
            options={
                'verbose_name': '管理员的登录信息',
                'verbose_name_plural': '管理员的登录信息',
                'db_table': 'manager_log_information',
            },
        ),
    ]
