# Generated by Django 3.2 on 2023-03-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='changeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=20, verbose_name='用户账号')),
                ('old_time', models.CharField(default='', max_length=20, verbose_name='原研学日期')),
                ('old_class', models.IntegerField(verbose_name='原研学大节')),
                ('new_time', models.CharField(default='', max_length=20, verbose_name='调换后研学日期')),
                ('new_class', models.IntegerField(verbose_name='调换后研学大节')),
                ('change_reason', models.CharField(default='', max_length=50, verbose_name='调换原因')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否已被删除')),
            ],
            options={
                'verbose_name': '用户的调换研学信息',
                'verbose_name_plural': '用户的调换研学信息',
                'db_table': 'users_change_data',
            },
        ),
        migrations.CreateModel(
            name='invitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_codes', models.CharField(default='', max_length=20, verbose_name='邀请码')),
            ],
            options={
                'verbose_name': '邀请码列表',
                'verbose_name_plural': '邀请码列表',
                'db_table': 'invitation_codes',
            },
        ),
        migrations.CreateModel(
            name='operateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=20, verbose_name='用户账号')),
                ('operate_time', models.IntegerField(default=0, verbose_name='用户操作次数')),
            ],
            options={
                'verbose_name': '用户的操作次数',
                'verbose_name_plural': '用户的操作次数',
                'db_table': 'users_operate_times',
            },
        ),
        migrations.CreateModel(
            name='SignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=20, verbose_name='用户账号')),
                ('user_pass', models.CharField(default='', max_length=30, verbose_name='用户密码')),
                ('user_name', models.CharField(default='', max_length=10, verbose_name='用户姓名')),
                ('user_sector', models.CharField(default='', max_length=10, verbose_name='用户部门方向')),
                ('user_period', models.IntegerField(max_length=7, verbose_name='用户期数')),
            ],
            options={
                'verbose_name': '用户注册和登录信息',
                'verbose_name_plural': '用户注册和登录信息',
                'db_table': 'user_sign_log_information',
            },
        ),
        migrations.CreateModel(
            name='theStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=20, verbose_name='用户账号')),
                ('study_date', models.CharField(default='', max_length=20, verbose_name='用户研学日期')),
                ('study_class', models.IntegerField(verbose_name='用户研学大节')),
                ('is_change', models.BooleanField(default=0, verbose_name='是否已调换')),
                ('is_leave', models.BooleanField(default=0, verbose_name='是否已请假')),
            ],
            options={
                'verbose_name': '用户的基础研学信息',
                'verbose_name_plural': '用户的基础研学信息',
                'db_table': 'base_study_data',
            },
        ),
    ]
