# Generated by Django 3.2 on 2023-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=20, verbose_name='用户账号')),
                ('leave_time', models.CharField(default='', max_length=20, verbose_name='请假的研学日期')),
                ('leave_class', models.IntegerField(verbose_name='请假的研学大节')),
                ('leave_reason', models.CharField(default='', max_length=50, verbose_name='请假原因')),
                ('is_delete', models.BooleanField(default=0, verbose_name='是否已被删除')),
            ],
            options={
                'verbose_name': '用户的研学请假信息',
                'verbose_name_plural': '用户的研学请假信息',
                'db_table': 'user_leave_data',
            },
        ),
    ]
