# Generated by Django 3.2 on 2023-03-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_leavedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signlog',
            name='user_pass',
            field=models.CharField(default='', max_length=100, verbose_name='用户密码'),
        ),
    ]
